apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-cluster
spec:
  destination:
    name: ''
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'capi-cluster/worker'
    repoURL: 'https://github.com/danieldn-aramada/bm-capi-gitops-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true