apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-cluster
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      valueFiles:
      - values.yaml
    path: 'colo/mgmt04/worker01'
    repoURL: 'https://github.com/danieldn-aramada/bm-capi-gitops-demo.git'
    targetRevision: helm
  project: default
  syncPolicy:
    automated:
      prune: true